"use client";
import { CompanyLogo } from "@/components/company-logo";
import type { ReactNode, RefObject } from "react";
import Link from "next/link";
import { ArrowUpRight, Bookmark, BriefcaseBusiness, Check, Clock3, MapPin, Search, X } from "lucide-react";
import type { JobDetail, JobSummary, StatusPatch } from "@/lib/contracts";
import { Button, buttonVariants } from "@/components/ui/button";
import { Sheet, SheetContent, SheetDescription, SheetHeader, SheetTitle } from "@/components/ui/sheet";
import { JobDescription } from "./job-description";
import { TechIcon } from "./tech-icon";
import { ThemeToggle } from "./theme-toggle";
export type Filter = "all" | "new-for-me" | "seen" | "saved" | "applied" | "rejected";
const filters: Record<Filter, string> = { all: "All roles", "new-for-me": "New for me", seen: "Seen", saved: "Saved", applied: "Applied", rejected: "Rejected" };
const date = (value: string | null | undefined) => value ? new Date(value).toLocaleDateString(undefined, { month: "short", day: "numeric", year: "numeric" }) : "Unknown";
type Enriched = { source?: string; last_seen_at?: string; experience?: string | null; seniority_origin?: string; extraction_state?: string };
type ViewJob = JobSummary & Enriched;
type Opener = RefObject<HTMLButtonElement | null>;
type RowProps = { job: ViewJob; openerRef: Opener; selectJob: (id: string | null) => void };
type ListProps = { filter: Filter; search: string; jobs: JobSummary[]; visible: JobSummary[]; loading: boolean; error: string; openerRef: Opener; selectJob: RowProps["selectJob"]; chooseFilter: (filter: Filter) => void; setSearch: (value: string) => void; reload: () => void; toolbar?: ReactNode; resultLimit?: number; sortLabel?: string; loadedUpdatedAt?: string | null };
type BodyProps = { detail: JobDetail | null; detailError: string; saving: boolean; rejecting: boolean; reason: string; setReason: (value: string) => void; setRejecting: (value: boolean) => void; changeStatus: (patch: StatusPatch) => Promise<void> };
type DrawerProps = BodyProps & { selected: string | null; openerRef: Opener; selectJob: RowProps["selectJob"] };

export function BoardHeader() { return <header className="border-b bg-background/90 backdrop-blur"><div className="mx-auto flex max-w-7xl items-center justify-between gap-4 px-5 py-4 sm:px-8"><Link href="/" className="flex items-center gap-3 font-semibold tracking-tight"><span aria-hidden="true" className="grid size-9 place-items-center rounded-xl bg-primary text-primary-foreground">J</span>Job Radar <span className="hidden font-normal text-muted-foreground sm:inline">/ Coach</span></Link><div className="flex items-center gap-2"><span className="hidden rounded-full bg-muted px-3 py-1 text-xs text-muted-foreground sm:inline">Your private workspace</span><ThemeToggle /></div></div></header> }
export function BoardHero({children}: {children?: ReactNode}) { return <div className="mb-8 flex flex-wrap items-end justify-between gap-5"><div><p className="mb-3 text-xs font-semibold tracking-[0.2em] text-primary">THE JOB SEARCH, WITH CONTEXT</p><h1 className="text-3xl font-semibold tracking-tight sm:text-5xl">Find your next good fit.</h1><p className="mt-4 max-w-xl text-sm leading-6 text-muted-foreground">Review the evidence, keep what matters, and make your next move.</p></div>{children}</div> }
const experienceStatus = (job: ViewJob) => job.experience ?? (job.description_available ? "Check description for experience" : "Description unavailable");
function Technology({job, limit}: {job: ViewJob; limit?: number}) { const shown = limit ? job.stack.slice(0, limit) : job.stack; return <span className="block"><span className="mb-2 block text-[10px] font-semibold uppercase tracking-wider text-muted-foreground">Technology</span><span className="flex flex-wrap gap-1.5">{shown.map((item) => <span key={item} className="inline-flex items-center gap-1 rounded-md bg-muted px-2 py-1 text-[11px] text-muted-foreground"><TechIcon name={item} />{item}</span>)}{limit && job.stack.length > limit && <span className="rounded-md bg-muted px-2 py-1 text-[11px] text-muted-foreground">+{job.stack.length - limit}</span>}{!shown.length && <span className="text-xs text-muted-foreground">{job.description_available ? "Stack not identified" : "Description unavailable"}</span>}</span></span> }
function JobCard({job, openerRef, selectJob}: RowProps) { const found = job.first_seen_at; return <button onClick={(event) => { openerRef.current = event.currentTarget; selectJob(job.id); }} className="group flex min-h-60 w-full flex-col rounded-2xl border bg-card p-5 text-left shadow-sm transition hover:-translate-y-0.5 hover:border-primary/40 hover:shadow-md focus-visible:outline-2 focus-visible:outline-offset-2"><span className="flex items-start justify-between gap-3"><CompanyLogo company={job.company} /><Bookmark aria-hidden="true" size={18} className={job.status === "saved" ? "fill-primary text-primary" : "text-muted-foreground"} /></span><span className="mt-4 block text-xs font-medium text-muted-foreground">{job.company}</span><span className="mt-1 block text-lg font-semibold leading-snug">{job.title}</span><span className="mt-3 flex items-center gap-1.5 text-xs text-muted-foreground"><MapPin size={13} aria-hidden="true" />{job.location ?? "Location not extracted"}</span><span className="mt-auto block pt-4"><Technology job={job} limit={4} /></span><span className="mt-4 grid gap-2 border-t pt-4 text-xs text-muted-foreground"><span className="grid grid-cols-[minmax(0,1fr)_auto] items-start gap-x-3 gap-y-1"><span className="grid h-14 min-w-0 content-start gap-1"><span className="flex items-start gap-1"><BriefcaseBusiness size={13} aria-hidden="true" className="mt-0.5 shrink-0" /><span className="line-clamp-2" title={experienceStatus(job)}>{experienceStatus(job)}</span></span>{job.seniority && <span className="truncate" title={`Level: ${job.seniority}`}>Level: {job.seniority}{job.seniority_origin === "title" ? " · title" : ""}</span>}</span><span className="whitespace-nowrap">{job.score === null ? (job.extraction_state === "extracted" ? "Not scored" : "Not analyzed") : `${job.score}/100`}</span></span><span className="flex min-h-8 items-start justify-between gap-2"><span className="inline-flex items-start gap-1"><Clock3 size={13} aria-hidden="true" className="mt-0.5 shrink-0" />{job.posted_at ? `Posted ${date(job.posted_at)} · Found ${date(found)}` : `Found ${date(found)}`}</span><span className="capitalize">{job.source ?? "Source unknown"}</span></span></span></button> }
function Placeholder({loading}: {loading: boolean}) { return <div className="grid min-h-[35rem] place-items-center px-6 py-16 text-center"><div>{loading ? <><div className="mx-auto size-8 animate-spin rounded-full border-2 border-muted border-t-primary" /><p className="mt-4 text-sm text-muted-foreground">Loading roles…</p></> : <><h2 className="text-xl font-medium">No roles in this view yet.</h2><p className="mt-2 text-sm text-muted-foreground">Try another filter or clear your search.</p></>}</div></div> }
export function JobsPanel({filter, search, jobs, visible, loading, error, openerRef, selectJob, chooseFilter, setSearch, reload, toolbar, resultLimit = 250, sortLabel, loadedUpdatedAt}: ListProps) { return <section aria-label="Job search"><div className="mb-5 flex flex-wrap items-center justify-between gap-3"><div className="flex max-w-full gap-1 overflow-x-auto" aria-label="Job filters">{(Object.keys(filters) as Filter[]).map((item) => <button key={item} aria-pressed={filter === item} onClick={() => item !== filter && chooseFilter(item)} className={`shrink-0 rounded-lg px-3 py-2 text-sm focus-visible:outline-2 focus-visible:outline-offset-2 ${filter === item ? "bg-primary text-primary-foreground" : "text-muted-foreground hover:bg-muted"}`}>{filters[item]}</button>)}</div><label className="flex w-full items-center gap-2 rounded-lg border bg-card px-3 py-2 sm:w-80"><Search size={16} aria-hidden="true" /><span className="sr-only">Search loaded jobs by title, company, or stack</span><input value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Search title, company, or stack" className="min-w-0 flex-1 bg-transparent text-sm outline-none" /></label></div>{toolbar}<div className="flex flex-wrap justify-between gap-2 py-4 text-xs text-muted-foreground"><span aria-live="polite">{loading ? "Loading roles…" : `${visible.length} ${visible.length === 1 ? "role" : "roles"}`}{jobs.length === resultLimit ? ` · latest ${resultLimit.toLocaleString()}` : ""}</span><span>{sortLabel ?? (filter === "new-for-me" ? "Ranked for you" : "Newest first")}{loadedUpdatedAt ? ` · Last observed ${new Date(loadedUpdatedAt).toLocaleString(undefined, {month:"short",day:"numeric",hour:"numeric",minute:"2-digit"})}` : ""}</span></div>{error ? <div role="alert" className="min-h-[35rem] rounded-2xl border border-destructive/20 bg-card p-6 text-sm text-destructive">{error}<Button variant="outline" className="ml-3" onClick={reload}>Retry</Button></div> : loading || visible.length === 0 ? <Placeholder loading={loading} /> : <div className="grid grid-cols-1 gap-4 md:grid-cols-2 xl:grid-cols-3">{visible.map((job) => <JobCard job={job} key={job.id} openerRef={openerRef} selectJob={selectJob} />)}</div>}</section> }
function ScoreReasons({reasons}: {reasons: JobDetail["reasons"]}) { if (!reasons.length) return null; return <section><h2 className="font-semibold">Why this score</h2><ul className="mt-3 space-y-3">{reasons.map((item) => <li key={item.factor} className="rounded-xl border bg-card p-4 text-sm"><span className="mb-1 block text-xs capitalize text-muted-foreground">{item.factor.replaceAll("_", " ")} · {item.assessment}</span>{item.detail}</li>)}</ul></section> }
function DetailBody({detail, detailError}: Pick<BodyProps, "detail" | "detailError">) { if (!detail) return <p className="p-6" role="status">{detailError || "Loading job…"}</p>; const job: JobDetail & Enriched = detail; return <div className="space-y-6 p-6">{detailError && <p role="alert" className="rounded-lg bg-destructive/10 p-3 text-sm text-destructive">{detailError}</p>}<div className="flex flex-wrap gap-2 text-xs"><span className="rounded-full bg-muted px-3 py-1 capitalize">{detail.status}</span><span className="rounded-full bg-muted px-3 py-1">{detail.location ?? "Location unknown"}</span><span className="rounded-full bg-muted px-3 py-1">{experienceStatus(job)}</span><span className="rounded-full bg-muted px-3 py-1">{detail.seniority ? `Level: ${detail.seniority}${job.seniority_origin === "title" ? " · title" : ""}` : "Seniority not specified"}</span><span className="rounded-full bg-muted px-3 py-1 capitalize">{job.source ?? "Source unknown"}</span></div><section><Technology job={job} /></section><div className="rounded-xl border bg-muted/60 p-5"><p className="text-xs uppercase tracking-wider text-muted-foreground">Fit assessment</p><p className="mt-2 text-3xl font-semibold">{detail.score === null ? "Not scored" : `${detail.score} / 100`}</p>{detail.fit_line && <p className="mt-3 text-sm leading-6">{detail.fit_line}</p>}{detail.recommendation && <p className="mt-2 text-sm capitalize">Recommendation: {detail.recommendation}</p>}</div><ScoreReasons reasons={detail.reasons} /><section><h2 className="mb-3 font-semibold">Job description</h2><JobDescription text={detail.raw_jd} /></section>{detail.status_reason && <p className="text-sm text-muted-foreground">Rejection reason: {detail.status_reason}</p>}</div> }
export function JobDrawer({selected, openerRef, selectJob, ...bodyProps}: DrawerProps) { const {detail, saving, rejecting, reason, setReason, setRejecting, changeStatus} = bodyProps; return <Sheet open={selected !== null} onOpenChange={(open) => !open && selectJob(null)}><SheetContent finalFocus={openerRef} className="flex overflow-hidden p-0 data-[side=right]:w-full data-[side=right]:sm:max-w-2xl"><div className="flex min-h-0 flex-1 flex-col"><SheetHeader className="shrink-0 border-b bg-background p-6 pr-12"><SheetTitle>{detail?.title ?? "Job details"}</SheetTitle><SheetDescription>{detail?.company ?? "Loading the role and its evidence…"}</SheetDescription></SheetHeader><div className="min-h-0 flex-1 overflow-y-auto"><DetailBody detail={detail} detailError={bodyProps.detailError} /></div><div className="shrink-0 border-t bg-background p-4"><div className="flex flex-wrap gap-2"><Button disabled={saving || !detail} onClick={() => changeStatus({ status: "saved" })}><Bookmark aria-hidden="true" />Save</Button><Button variant="outline" disabled={saving || !detail} onClick={() => changeStatus({ status: "applied" })}><Check aria-hidden="true" />Applied</Button><Button variant="outline" disabled={saving || !detail} onClick={() => setRejecting(true)}><X aria-hidden="true" />Reject</Button>{detail && <a className={buttonVariants({ variant: "outline" })} href={detail.apply_url ?? detail.url} target="_blank" rel="noopener noreferrer">Original <ArrowUpRight aria-hidden="true" /></a>}</div>{rejecting && <form onSubmit={(event) => { event.preventDefault(); if (reason.trim()) changeStatus({ status: "rejected", reason }); }} className="mt-3 flex flex-wrap gap-2"><label htmlFor="reject-reason" className="sr-only">Why isn’t this a fit?</label><input id="reject-reason" required maxLength={2000} value={reason} onChange={(event) => setReason(event.target.value)} placeholder="Why isn’t this a fit?" className="min-w-48 flex-1 rounded-lg border bg-background px-3 text-sm" /><Button disabled={saving || !reason.trim()} type="submit">Confirm</Button><Button variant="ghost" type="button" onClick={() => setRejecting(false)}>Cancel</Button></form>}</div></div></SheetContent></Sheet> }
