export type TechnologyIcon = {
  asset: string;
  color: string;
  wide?: boolean;
};

const BRAND_ICONS = {
  "aerospike": { asset: "aerospike", color: "#c21417" },
  "alpinedotjs": { asset: "alpinedotjs", color: "#8bc0d0" },
  "android": { asset: "android", color: "#3ddc84" },
  "angular": { asset: "angular", color: "currentColor" },
  "angularmaterial": { asset: "angularmaterial", color: "#ffa726" },
  "ansible": { asset: "ansible", color: "#ee0000" },
  "anthropic": { asset: "anthropic", color: "currentColor" },
  "apacheairflow": { asset: "apacheairflow", color: "#017cee" },
  "apachekafka": { asset: "apachekafka", color: "currentColor" },
  "apachespark": { asset: "apachespark", color: "#e25a1c" },
  "argo": { asset: "argo", color: "#ef7b4d" },
  "argocd": { asset: "argocd", color: "#ef7b4d" },
  "arm": { asset: "arm", color: "#0091bd" },
  "autocad": { asset: "autocad", color: "#e51050" },
  "aws": { asset: "aws", color: "#ff9900", wide: true },
  "azure": { asset: "azure", color: "#0078d4" },
  "azuredevops": { asset: "azuredevops", color: "#0078d4" },
  "bash": { asset: "bash", color: "currentColor" },
  "bazel": { asset: "bazel", color: "#43a047" },
  "bentoml": { asset: "bentoml", color: "currentColor" },
  "bitbucket": { asset: "bitbucket", color: "#0052cc" },
  "c": { asset: "c", color: "#a8b9cc" },
  "cassandra": { asset: "cassandra", color: "#1185b0" },
  "celery": { asset: "celery", color: "#37814a" },
  "ceph": { asset: "ceph", color: "#ef5c55" },
  "circleci": { asset: "circleci", color: "currentColor" },
  "claude": { asset: "claude", color: "#d97757" },
  "claudecode": { asset: "claudecode", color: "#d97757" },
  "clickhouse": { asset: "clickhouse", color: "#ffcc01" },
  "cloudrun": { asset: "cloudrun", color: "#4285f4" },
  "confluence": { asset: "confluence", color: "#172b4d" },
  "consul": { asset: "consul", color: "#f24c53" },
  "contentful": { asset: "contentful", color: "#2478cc" },
  "cplusplus": { asset: "cplusplus", color: "#00599c" },
  "crewai": { asset: "crewai", color: "#ff5a50" },
  "csharp": { asset: "csharp", color: "#68217a" },
  "css": { asset: "css", color: "#663399" },
  "css3": { asset: "css3", color: "#3d8fc6" },
  "cssmodules": { asset: "cssmodules", color: "currentColor" },
  "cursor": { asset: "cursor", color: "currentColor" },
  "cypress": { asset: "cypress", color: "#69d3a7" },
  "databricks": { asset: "databricks", color: "#ff3621" },
  "datadog": { asset: "datadog", color: "#632ca6" },
  "django": { asset: "django", color: "currentColor" },
  "docker": { asset: "docker", color: "#2496ed" },
  "dotnet": { asset: "dotnet", color: "#512bd4" },
  "dotnetcore": { asset: "dotnetcore", color: "#623697" },
  "duckdb": { asset: "duckdb", color: "#fff000" },
  "dynamodb": { asset: "dynamodb", color: "#527fff" },
  "eclipse": { asset: "eclipse", color: "#2c2255" },
  "elastic": { asset: "elastic", color: "#005571" },
  "elasticsearch": { asset: "elasticsearch", color: "#005571" },
  "envoy": { asset: "envoy", color: "#e13eaf" },
  "express": { asset: "express", color: "currentColor" },
  "fastapi": { asset: "fastapi", color: "#009688" },
  "ffmpeg": { asset: "ffmpeg", color: "#007808" },
  "fluentd": { asset: "fluentd", color: "#0e83c8" },
  "flux": { asset: "flux", color: "#5468ff" },
  "git": { asset: "git", color: "#f03c2e" },
  "github": { asset: "github", color: "currentColor" },
  "githubactions": { asset: "githubactions", color: "#2088ff" },
  "githubcopilot": { asset: "githubcopilot", color: "currentColor" },
  "gitlab": { asset: "gitlab", color: "#fc6d26" },
  "go": { asset: "go", color: "#00add8" },
  "googleads": { asset: "googleads", color: "#4285f4" },
  "googleanalytics": { asset: "googleanalytics", color: "#e37400" },
  "googlebigquery": { asset: "googlebigquery", color: "#669df6" },
  "googlecloud": { asset: "googlecloud", color: "#4285f4" },
  "googlegemini": { asset: "googlegemini", color: "#8e75b2" },
  "googlepubsub": { asset: "googlepubsub", color: "#aecbfa" },
  "gradle": { asset: "gradle", color: "currentColor" },
  "grafana": { asset: "grafana", color: "#f46800" },
  "graphql": { asset: "graphql", color: "currentColor" },
  "grpc": { asset: "grpc", color: "#00b0ad" },
  "grunt": { asset: "grunt", color: "#faa918" },
  "hadoop": { asset: "hadoop", color: "#ffff00" },
  "helm": { asset: "helm", color: "#0f1689" },
  "html5": { asset: "html5", color: "#e34f26" },
  "hubspot": { asset: "hubspot", color: "#ff7a59" },
  "huggingface": { asset: "huggingface", color: "#ffd21e" },
  "illustrator": { asset: "illustrator", color: "currentColor" },
  "ios": { asset: "ios", color: "currentColor" },
  "istio": { asset: "istio", color: "#466bb0" },
  "jaeger": { asset: "jaeger", color: "#66cfe3" },
  "jasmine": { asset: "jasmine", color: "#8a4182" },
  "java": { asset: "java", color: "#EA2D2E" },
  "javascript": { asset: "javascript", color: "#f7df1e" },
  "jenkins": { asset: "jenkins", color: "#d24939" },
  "jest": { asset: "jest", color: "#c21325" },
  "jira": { asset: "jira", color: "#0052cc" },
  "json": { asset: "json", color: "currentColor" },
  "junit": { asset: "junit", color: "#dc514a" },
  "kotlin": { asset: "kotlin", color: "#7f52ff" },
  "kubeflow": { asset: "kubeflow", color: "#72a1e5" },
  "kubernetes": { asset: "kubernetes", color: "#326ce5" },
  "langchain": { asset: "langchain", color: "#7fc8ff" },
  "langgraph": { asset: "langgraph", color: "#7fc8ff" },
  "laravel": { asset: "laravel", color: "#ff2d20" },
  "lighthouse": { asset: "lighthouse", color: "#f44b21" },
  "linux": { asset: "linux", color: "#fcc624" },
  "longhorn": { asset: "longhorn", color: "#5f224b" },
  "macos": { asset: "macos", color: "currentColor" },
  "maven": { asset: "maven", color: "#e97826" },
  "metabase": { asset: "metabase", color: "#509ee3" },
  "microsoftsqlserver": { asset: "microsoftsqlserver", color: "#ee352c" },
  "microstation": { asset: "microstation", color: "#62bb47" },
  "milvus": { asset: "milvus", color: "#00a1ea" },
  "minitab": { asset: "minitab", color: "#8dc63f" },
  "mlflow": { asset: "mlflow", color: "#0194e2" },
  "modelcontextprotocol": { asset: "modelcontextprotocol", color: "currentColor" },
  "mongodb": { asset: "mongodb", color: "#47a248" },
  "mysql": { asset: "mysql", color: "#4479a1" },
  "n8n": { asset: "n8n", color: "#ea4b71" },
  "nats": { asset: "nats", color: "#27aae1" },
  "neo4j": { asset: "neo4j", color: "#4581c3" },
  "nestjs": { asset: "nestjs", color: "#e0234e" },
  "netlify": { asset: "netlify", color: "#00c7b7" },
  "nextdotjs": { asset: "nextdotjs", color: "currentColor" },
  "nginx": { asset: "nginx", color: "#009639" },
  "nodedotjs": { asset: "nodedotjs", color: "#5fa04e" },
  "nodered": { asset: "nodered", color: "#8f0000" },
  "nomad": { asset: "nomad", color: "#00ca8e" },
  "npm": { asset: "npm", color: "#cb3837" },
  "numpy": { asset: "numpy", color: "#013243" },
  "nuxt": { asset: "nuxt", color: "#00dc82" },
  "oauth": { asset: "oauth", color: "currentColor" },
  "objectivec": { asset: "objectivec", color: "#0b5a9d" },
  "onnx": { asset: "onnx", color: "#005ced" },
  "openai": { asset: "openai", color: "currentColor" },
  "opensearch": { asset: "opensearch", color: "#005eb8" },
  "opentelemetry": { asset: "opentelemetry", color: "currentColor" },
  "oracle": { asset: "oracle", color: "#EA1B22" },
  "packer": { asset: "packer", color: "#02a8ef" },
  "pandas": { asset: "pandas", color: "#150458" },
  "photoshop": { asset: "photoshop", color: "currentColor" },
  "php": { asset: "php", color: "#777bb4" },
  "pinecone": { asset: "pinecone", color: "#0b8f79", wide: true },
  "pino": { asset: "pino", color: "#687634" },
  "playwright": { asset: "playwright", color: "#2EAD33" },
  "postgresql": { asset: "postgresql", color: "#4169e1" },
  "powershell": { asset: "powershell", color: "currentColor" },
  "prefect": { asset: "prefect", color: "currentColor" },
  "prisma": { asset: "prisma", color: "#2d3748" },
  "prometheus": { asset: "prometheus", color: "#e6522c" },
  "proxmox": { asset: "proxmox", color: "#e57000" },
  "pulumi": { asset: "pulumi", color: "#8a3391" },
  "puppet": { asset: "puppet", color: "#ffae1a" },
  "pusher": { asset: "pusher", color: "#300d4f" },
  "python": { asset: "python", color: "#3776ab" },
  "pytorch": { asset: "pytorch", color: "#ee4c2c" },
  "qdrant": { asset: "qdrant", color: "#dc244c" },
  "rabbitmq": { asset: "rabbitmq", color: "#ff6600" },
  "ray": { asset: "ray", color: "#028cf0" },
  "react": { asset: "react", color: "#61dafb" },
  "reactivex": { asset: "reactivex", color: "#b7178c" },
  "redhat": { asset: "redhat", color: "#ee0000" },
  "redis": { asset: "redis", color: "#ff4438" },
  "redux": { asset: "redux", color: "#764abc" },
  "remix": { asset: "remix", color: "currentColor" },
  "rocksdb": { asset: "rocksdb", color: "currentColor" },
  "rollup": { asset: "rollup", color: "#ff3333" },
  "rook": { asset: "rook", color: "#2ac6ea" },
  "ros": { asset: "ros", color: "#22314e" },
  "ruby": { asset: "ruby", color: "#cc342d" },
  "rubyonrails": { asset: "rubyonrails", color: "#d30001" },
  "rust": { asset: "rust", color: "currentColor" },
  "salesforce": { asset: "salesforce", color: "#00a1e0" },
  "sanity": { asset: "sanity", color: "currentColor" },
  "sass": { asset: "sass", color: "#cc6699" },
  "scala": { asset: "scala", color: "#dc322f" },
  "scikitlearn": { asset: "scikitlearn", color: "#f7931e" },
  "scipy": { asset: "scipy", color: "#8caae6" },
  "scylladb": { asset: "scylladb", color: "#6cd5e7" },
  "selenium": { asset: "selenium", color: "#43b02a" },
  "sentry": { asset: "sentry", color: "#362d59" },
  "serverless": { asset: "serverless", color: "#fd5750" },
  "shopify": { asset: "shopify", color: "#7ab55c" },
  "sketch": { asset: "sketch", color: "#f7b500" },
  "slack": { asset: "slack", color: "currentColor" },
  "snowflake": { asset: "snowflake", color: "#29b5e8" },
  "socketdotio": { asset: "socketdotio", color: "currentColor" },
  "sonarqubeserver": { asset: "sonarqubeserver", color: "#126ed3" },
  "spring": { asset: "spring", color: "#6db33f" },
  "springboot": { asset: "springboot", color: "#6db33f" },
  "ssh": { asset: "ssh", color: "currentColor" },
  "storybook": { asset: "storybook", color: "#ff4785" },
  "styledcomponents": { asset: "styledcomponents", color: "#db7093" },
  "svelte": { asset: "svelte", color: "#ff3e00" },
  "symfony": { asset: "symfony", color: "currentColor" },
  "tailwindcss": { asset: "tailwindcss", color: "#06b6d4" },
  "teamcity": { asset: "teamcity", color: "currentColor" },
  "temporal": { asset: "temporal", color: "currentColor" },
  "tensorflow": { asset: "tensorflow", color: "#ff6f00" },
  "terraform": { asset: "terraform", color: "#844fba" },
  "thanos": { asset: "thanos", color: "#6d41ff" },
  "travisci": { asset: "travisci", color: "#3eaaaf" },
  "trpc": { asset: "trpc", color: "#2596be" },
  "twilio": { asset: "twilio", color: "#f22f46" },
  "typescript": { asset: "typescript", color: "#3178c6" },
  "unix": { asset: "unix", color: "#4051b5" },
  "vagrant": { asset: "vagrant", color: "#1868f2" },
  "vault": { asset: "vault", color: "#ffec6e" },
  "vercel": { asset: "vercel", color: "currentColor" },
  "vite": { asset: "vite", color: "#9135ff" },
  "vitest": { asset: "vitest", color: "#00ff74" },
  "vllm": { asset: "vllm", color: "#30a2ff" },
  "vmware": { asset: "vmware", color: "#607078" },
  "vscode": { asset: "vscode", color: "#3C99D4" },
  "vuedotjs": { asset: "vuedotjs", color: "#4fc08d" },
  "weaviate": { asset: "weaviate", color: "#00a98f" },
  "webpack": { asset: "webpack", color: "#8dd6f9" },
  "webrtc": { asset: "webrtc", color: "currentColor" },
  "weightsandbiases": { asset: "weightsandbiases", color: "#ffbe00" },
  "windsurf": { asset: "windsurf", color: "currentColor" },
  "xml": { asset: "xml", color: "#005fad" },
  "xyflow": { asset: "xyflow", color: "currentColor" },
  "yaml": { asset: "yaml", color: "#cb171e" },
  "zapier": { asset: "zapier", color: "#ff4f00" },
  "zustand": { asset: "zustand", color: "#443e38" },
} as const satisfies Record<string, TechnologyIcon>;

const BRAND_ALIASES: Record<string, keyof typeof BRAND_ICONS> = {
  ".net": "dotnet",
  ".net core": "dotnetcore",
  "adobe illustrator": "illustrator",
  "aerospike": "aerospike",
  "airflow": "apacheairflow",
  "alpine.js": "alpinedotjs",
  "amazon web services": "aws",
  "amazon web services (aws)": "aws",
  "android": "android",
  "angular": "angular",
  "angular material": "angularmaterial",
  "ansible": "ansible",
  "anthropic": "anthropic",
  "apache kafka": "apachekafka",
  "apache spark": "apachespark",
  "argo": "argo",
  "argo cd": "argocd",
  "argocd": "argocd",
  "arm": "arm",
  "autocad": "autocad",
  "aws": "aws",
  "azure": "azure",
  "azure devops": "azuredevops",
  "bash": "bash",
  "bazel": "bazel",
  "bentoml": "bentoml",
  "bigquery": "googlebigquery",
  "bitbucket": "bitbucket",
  "c": "c",
  "c#": "csharp",
  "c++": "cplusplus",
  "cassandra": "cassandra",
  "celery": "celery",
  "ceph": "ceph",
  "chatgpt": "openai",
  "circleci": "circleci",
  "claude": "claude",
  "claude code": "claudecode",
  "clickhouse": "clickhouse",
  "cloud run": "cloudrun",
  "codex": "openai",
  "confluence": "confluence",
  "consul": "consul",
  "contentful": "contentful",
  "crewai": "crewai",
  "css": "css",
  "css modules": "cssmodules",
  "css3": "css3",
  "cursor": "cursor",
  "cypress": "cypress",
  "databricks": "databricks",
  "datadog": "datadog",
  "django": "django",
  "docker": "docker",
  "duckdb": "duckdb",
  "dynamodb": "dynamodb",
  "eclipse": "eclipse",
  "elastic": "elastic",
  "elasticsearch": "elasticsearch",
  "envoy": "envoy",
  "express": "express",
  "express.js": "express",
  "fastapi": "fastapi",
  "ffmpeg": "ffmpeg",
  "fluentd": "fluentd",
  "flux": "flux",
  "gcp": "googlecloud",
  "gemini": "googlegemini",
  "gemini cli": "googlegemini",
  "git": "git",
  "github": "github",
  "github actions": "githubactions",
  "github copilot": "githubcopilot",
  "gitlab": "gitlab",
  "gitlab ci": "gitlab",
  "gitlab ci/cd": "gitlab",
  "gitlab-ci": "gitlab",
  "go": "go",
  "go (golang)": "go",
  "golang": "go",
  "google ads": "googleads",
  "google analytics": "googleanalytics",
  "google cloud": "googlecloud",
  "google cloud platform": "googlecloud",
  "google gemini": "googlegemini",
  "google pub/sub": "googlepubsub",
  "gpt": "openai",
  "gradle": "gradle",
  "grafana": "grafana",
  "graphql": "graphql",
  "graphql api": "graphql",
  "grpc": "grpc",
  "grunt": "grunt",
  "hadoop": "hadoop",
  "helm": "helm",
  "html": "html5",
  "html5": "html5",
  "hubspot": "hubspot",
  "hugging face": "huggingface",
  "huggingface": "huggingface",
  "ios": "ios",
  "istio": "istio",
  "jaeger": "jaeger",
  "jasmine": "jasmine",
  "java": "java",
  "javascript": "javascript",
  "jenkins": "jenkins",
  "jest": "jest",
  "jira": "jira",
  "json": "json",
  "junit": "junit",
  "k8s": "kubernetes",
  "kafka": "apachekafka",
  "kotlin": "kotlin",
  "kubeflow": "kubeflow",
  "kubernetes": "kubernetes",
  "langchain": "langchain",
  "langgraph": "langgraph",
  "laravel": "laravel",
  "lighthouse": "lighthouse",
  "linux": "linux",
  "longhorn": "longhorn",
  "macos": "macos",
  "maven": "maven",
  "mcp": "modelcontextprotocol",
  "metabase": "metabase",
  "microsoft azure": "azure",
  "microsoft cloud": "azure",
  "microstation": "microstation",
  "milvus": "milvus",
  "minitab": "minitab",
  "mlflow": "mlflow",
  "mongodb": "mongodb",
  "mssql": "microsoftsqlserver",
  "mysql": "mysql",
  "n8n": "n8n",
  "nats": "nats",
  "neo4j": "neo4j",
  "nestjs": "nestjs",
  "netlify": "netlify",
  "next.js": "nextdotjs",
  "nextjs": "nextdotjs",
  "nginx": "nginx",
  "node-red": "nodered",
  "node.js": "nodedotjs",
  "nodejs": "nodedotjs",
  "nomad": "nomad",
  "npm": "npm",
  "numpy": "numpy",
  "nuxt.js": "nuxt",
  "oauth": "oauth",
  "oauth2": "oauth",
  "objective-c": "objectivec",
  "onnx": "onnx",
  "openai": "openai",
  "opensearch": "opensearch",
  "opentelemetry": "opentelemetry",
  "oracle": "oracle",
  "packer": "packer",
  "pandas": "pandas",
  "photoshop": "photoshop",
  "php": "php",
  "pinecone": "pinecone",
  "pino": "pino",
  "playwright": "playwright",
  "postgres": "postgresql",
  "postgresql": "postgresql",
  "powershell": "powershell",
  "prefect": "prefect",
  "prisma": "prisma",
  "prometheus": "prometheus",
  "proxmox": "proxmox",
  "pulumi": "pulumi",
  "puppet": "puppet",
  "pusher": "pusher",
  "pyspark": "apachespark",
  "python": "python",
  "pytorch": "pytorch",
  "qdrant": "qdrant",
  "rabbitmq": "rabbitmq",
  "ray": "ray",
  "react": "react",
  "react flow": "xyflow",
  "react native": "react",
  "react.js": "react",
  "redhat": "redhat",
  "redis": "redis",
  "redux": "redux",
  "remix": "remix",
  "rocksdb": "rocksdb",
  "rollup": "rollup",
  "rook": "rook",
  "ros": "ros",
  "ros/ros2": "ros",
  "ros2": "ros",
  "ruby": "ruby",
  "ruby on rails": "rubyonrails",
  "rust": "rust",
  "rxjs": "reactivex",
  "salesforce": "salesforce",
  "sanity": "sanity",
  "sass": "sass",
  "scala": "scala",
  "scikit-learn": "scikitlearn",
  "scipy": "scipy",
  "scss": "sass",
  "scylladb": "scylladb",
  "selenium": "selenium",
  "sentry": "sentry",
  "serverless": "serverless",
  "shopify": "shopify",
  "sketch": "sketch",
  "slack": "slack",
  "snowflake": "snowflake",
  "socket.io": "socketdotio",
  "sonarqube": "sonarqubeserver",
  "spark": "apachespark",
  "spring": "spring",
  "spring boot": "springboot",
  "sql server": "microsoftsqlserver",
  "ssh": "ssh",
  "storybook": "storybook",
  "styled components": "styledcomponents",
  "svelte": "svelte",
  "symfony": "symfony",
  "tailwind css": "tailwindcss",
  "teamcity": "teamcity",
  "temporal": "temporal",
  "tensorflow": "tensorflow",
  "terraform": "terraform",
  "thanos": "thanos",
  "travis-ci": "travisci",
  "trpc": "trpc",
  "twilio": "twilio",
  "typescript": "typescript",
  "unix": "unix",
  "vagrant": "vagrant",
  "vault": "vault",
  "vercel": "vercel",
  "vite": "vite",
  "vitest": "vitest",
  "vllm": "vllm",
  "vmware": "vmware",
  "vscode": "vscode",
  "vue": "vuedotjs",
  "vue.js": "vuedotjs",
  "weaviate": "weaviate",
  "webpack": "webpack",
  "webrtc": "webrtc",
  "weights & biases": "weightsandbiases",
  "windsurf": "windsurf",
  "xml": "xml",
  "yaml": "yaml",
  "zapier": "zapier",
  "zustand": "zustand",
};

const CONCEPT_TERMS = new Set([
  "2.5d/3d integration",
  "2d/3d modeling",
  "advanced parametric 3d cad systems",
  "agent frameworks",
  "agent sdk",
  "agent sdks",
  "agent/eval frameworks",
  "agentic ai",
  "agentic and autonomous workflows",
  "agentic appsec platform",
  "agentic development",
  "agentic evaluation frameworks",
  "agentic frameworks",
  "agentic systems",
  "agentic workflows",
  "agents",
  "ai",
  "ai agent systems",
  "ai agents",
  "ai engineering",
  "ai frameworks",
  "ai systems",
  "ai-assisted development tools",
  "ai-assisted engineering tools",
  "ai-driven workflows",
  "ai/ml",
  "ai/ml frameworks",
  "airborne platforms",
  "api",
  "apis",
  "artificial intelligence",
  "attacker-defender frameworks",
  "automated sortation systems",
  "automated testing",
  "automation",
  "automation pipelines",
  "backend engineering",
  "bi platforms",
  "chiplet-based architectures",
  "ci/cd",
  "ci/cd pipelines",
  "cli tools",
  "cloud",
  "cloud ai services",
  "cloud platforms",
  "cloud services",
  "cloud-based architectures",
  "cloud-based development environments",
  "cloud-native architectures",
  "combustion engine testing and calibration",
  "command-line interfaces (cli)",
  "communication protocols",
  "computer vision",
  "containerization",
  "containers",
  "continuous integration/continuous deployment (ci/cd) pipelines",
  "control systems",
  "cooling and energy systems",
  "cpu architecture",
  "data analysis",
  "data engineering",
  "data structures",
  "databases",
  "deep learning",
  "devops",
  "diesel after-treatment systems",
  "disa’s big data platform",
  "distributed computing",
  "distributed systems",
  "document retrieval",
  "dvp testing",
  "electrical engineering",
  "electrified hybrid systems",
  "embedded systems",
  "embedding-based search",
  "embeddings",
  "entity framework",
  "evals",
  "evaluation frameworks",
  "event-driven systems",
  "firmware",
  "foundation model operations (fmops)",
  "foundation model pipelines",
  "foundation models",
  "frameworks",
  "full stack frameworks",
  "full-stack development",
  "gen ai",
  "genai",
  "generative ai",
  "generative ai frameworks",
  "goods-to-person picking systems",
  "grpc services",
  "hardware architecture",
  "headless cms platforms",
  "heterogeneous integration",
  "high-power laser systems",
  "high-speed interfaces",
  "hortonworks data platform",
  "human-in-the-loop workflows",
  "hybrid search",
  "information retrieval",
  "infrastructure and production systems",
  "infrastructure-as-code",
  "large language model",
  "large language models",
  "large language models (llms)",
  "large-scale system design",
  "linux-based systems",
  "llm",
  "llm api",
  "llm apis",
  "llms",
  "machine learning",
  "marketing automation",
  "microservices",
  "microservices architectures",
  "ml",
  "mlops",
  "model context protocol (mcp)",
  "model-serving interfaces",
  "multi-agent architectures",
  "multi-agent systems",
  "multi-step agentic workflows",
  "multimodal models",
  "natural language processing",
  "networking",
  "networking and security protocols",
  "neural network inference pipelines",
  "nlp",
  "nosql",
  "observability",
  "operating systems",
  "power conversion systems",
  "predictive modeling",
  "prompt and context engineering",
  "prompt engineering",
  "protocol buffers",
  "rag",
  "rag systems",
  "react testing library",
  "real-time operating systems (rtos)",
  "relational",
  "relational databases",
  "rest",
  "rest api",
  "rest apis",
  "rest web services",
  "restful api",
  "restful apis",
  "retrieval augmented generation",
  "retrieval systems",
  "retrieval-augmented generation",
  "retrieval-augmented generation (rag)",
  "robotics systems",
  "ros-based robotic systems",
  "security",
  "semantic search",
  "server-side development",
  "service cloud",
  "service-oriented architectures",
  "shell scripting",
  "shuttle systems",
  "software testing",
  "sql",
  "ssr frameworks",
  "statistical modeling and inference",
  "structured data integration",
  "structured outputs",
  "system design",
  "systems of systems",
  "testing",
  "testing frameworks",
  "threat modeling",
  "tool use",
  "tool-calling",
  "tool-use",
  "unix-like operating systems",
  "user interface design",
  "vector database",
  "vector databases",
  "vector db",
  "vector search",
  "vector stores",
  "version control",
  "vla-based systems",
  "websockets",
  "workflow",
  "workflow orchestration",
  "workflows",
  "zero trust architectures",
]);

export function normalizedTechnologyName(name: string): string {
  return name.trim().replace(/\s+/g, " ").toLocaleLowerCase("en-US");
}

export function technologyIconFor(name: string): TechnologyIcon | null {
  const normalized = normalizedTechnologyName(name);
  const exact = BRAND_ALIASES[normalized];
  if (exact) return BRAND_ICONS[exact];
  if (/^gpt(?:\b|[- .]?\d)/.test(normalized)) return BRAND_ICONS.openai;
  if (/^claude(?:\b|[- .]?\d)/.test(normalized)) return BRAND_ICONS.claude;
  if (/^gemini(?:\b|[- .]?\d)/.test(normalized)) return BRAND_ICONS.googlegemini;
  return null;
}

export function technologyKind(name: string): "brand" | "concept" | "text" {
  if (technologyIconFor(name)) return "brand";
  return CONCEPT_TERMS.has(normalizedTechnologyName(name)) ? "concept" : "text";
}

export function uniqueTechnologyNames(names: readonly string[]): string[] {
  const seen = new Set<string>();
  const result: string[] = [];
  for (const raw of names) {
    const name = raw.trim().replace(/\s+/g, " ");
    const key = normalizedTechnologyName(name);
    if (!key || seen.has(key)) continue;
    seen.add(key);
    result.push(name);
  }
  return result;
}

export function technologyChipWindow(
  names: readonly string[], limit: number, expanded: boolean,
): { visibleNames: string[]; hiddenCount: number; collapsedLimit: number } {
  const allNames = uniqueTechnologyNames(names);
  const collapsedLimit = Number.isFinite(limit) ? Math.max(1, Math.trunc(limit)) : 4;
  return {
    visibleNames: expanded ? allNames : allNames.slice(0, collapsedLimit),
    hiddenCount: expanded ? 0 : Math.max(0, allNames.length - collapsedLimit),
    collapsedLimit,
  };
}
