// Offline audit: the caller supplies a SELECT-only hosted snapshot. Never prints job copy or contact details.
import { readFileSync, writeFileSync } from "node:fs";
import { pathToFileURL } from "node:url";
import catalog from "../ui/lib/company-logo-catalog.json";
import domains from "../ui/lib/company-logo-domains.json";
import type { CompanyLogoIdentity } from "../ui/lib/company-logos";
import identities from "../ui/lib/company-logo-identities.json";
import { canonicalCompanyName, postingCompanyDomains, postingSourceCompanies } from "../ui/lib/company-logos";

type Posting = { id: string; company: string; url: string | null; apply_url: string | null; raw_jd: string | null };
type AuditEntry = { name: string; source: string; expected: readonly string[]; expectedSources: readonly string[]; postings: { id: string; evidence: string[]; sourceCompanies: string[]; conflicts: string[] }[] };
const domainMap: Record<string, string | null> = domains;
const identityMap: Readonly<Record<string, CompanyLogoIdentity>> = identities;

export function auditLogoCollisions(rows: Posting[]): AuditEntry[] {
  const grouped = new Map<string, Posting[]>();
  for (const row of rows) {
    const name = canonicalCompanyName(row.company);
    const group = grouped.get(name) ?? [];
    group.push(row); grouped.set(name, group);
  }
  return [...new Set([...Object.keys(catalog), ...Object.keys(domains)])].sort().map(name => {
    const expected = Object.hasOwn(identityMap, name) ? identityMap[name].domains : domainMap[name] ? [domainMap[name]!] : [];
    const expectedSources = identityMap[name]?.sourceCompanies ?? [];
    return { name, source: Object.hasOwn(catalog, name) ? "catalog" : "domain map", expected, expectedSources,
      postings: (grouped.get(name) ?? []).map(row => {
        const evidence = postingCompanyDomains({ company: row.company, applyUrl: row.apply_url, url: row.url });
        const sourceCompanies = postingSourceCompanies({ company: row.company, postingId: row.id, applyUrl: row.apply_url, url: row.url });
        return { id: row.id, evidence, sourceCompanies, conflicts: [...(expected.length ? evidence.filter(domain => !expected.includes(domain)) : []), ...(expectedSources.length ? sourceCompanies.filter(company => !expectedSources.includes(company)) : [])] };
      }) };
  });
}

if (process.argv[1] && import.meta.url === pathToFileURL(process.argv[1]).href) {
  const [input, output] = process.argv.slice(2);
  if (!input || !output) throw new Error("Usage: audit-logo-collisions.ts <private snapshot.json> <report.md>");
  const rows: Posting[] = JSON.parse(readFileSync(input, "utf8"));
  const entries = auditLogoCollisions(rows);
  const conflicts = entries.flatMap(entry => entry.postings.filter(p => p.conflicts.length).map(p => ({ name: entry.name, ...p })));
  const lines = ["# Logo name collision audit — 2026-10-07", "", "Generated by `scripts/audit-logo-collisions.ts`; do not edit the inventory by hand.", "",
    `SELECT-only hosted snapshot: ${rows.length} postings. Catalog: ${Object.keys(catalog).length} entries; domain map: ${Object.keys(domains).length}; union audited: ${entries.length}.`, "",
    "Query: `select id,company,url,apply_url,raw_jd from public.postings order by id` via the Supabase management API with `read_only: true`. Existing environment credential; no secret-manager prompts, hosted writes, homepage guesses, or Logo.dev calls.", "",
    `Detected ${conflicts.length} structured posting identity conflicts. Domains come only from posting/apply URLs; source-company IDs come from ATS tenants and verified employer headings bound to posting IDs. JD text grants and vetoes nothing.`, "",
    "The Doit/DoiT collision is independently corroborated by the source-page employer heading: the incident posting suffix aae3e321 links linkedin:doit-official, while all six DoiT rows link linkedin:doitintl. The catalog manifest's source page also links doitintl. Only doit.com, verified doitintl source-company identifiers or asset source posting IDs can select the DoiT image; a bare name cannot.", "",
    "Ordinary catalog and audited domain-map names remain usable without conflicting structured evidence. Known collision names require positive identity. Initials overrides continue to block the earlier wrong-brand and placeholder names. Structured source-company bindings are generated offline by scripts/build-logo-source-bindings.ts; raw JD/contact data is never emitted.", "",
    "## Structured identity conflicts", "", "| Name | Posting id | Expected domain or company identifier | Conflicting identity |", "| --- | --- | --- | --- |",
    ...conflicts.map(p => `| ${p.name} | ${p.id} | ${entries.find(e => e.name === p.name)!.expected.concat(entries.find(e => e.name === p.name)!.expectedSources).join(", ")} | ${p.conflicts.join(", ")} |`), "",
    "## Complete entry inventory", "",
    "Every catalog/domain key is listed below. Raw job copy and contact details are omitted. A dash means no structured domain or employer identifier is available. Ordinary catalog names retain their existing mark absent a conflict; known collisions require positive identity.", "",
    "| Name | Source | Bound domains | Hosted posting ids and domain evidence |", "| --- | --- | --- | --- |",
    ...entries.map(e => `| ${e.name.replaceAll("|", "\\|")} | ${e.source} | ${[...e.expected, ...e.expectedSources].join(", ") || "no bound identity"} | ${e.postings.map(p => `${p.id}: ${[...p.evidence, ...p.sourceCompanies].join(", ") || "—"}`).join("; ") || "no matching postings"} |`), ""];
  writeFileSync(output, lines.join("\n"));
  console.log(JSON.stringify({ totalPostings: rows.length, entries: entries.length, matchedPostings: entries.reduce((sum, e) => sum + e.postings.length, 0), conflicts }, null, 2));
}
