// Offline audit: the caller supplies a SELECT-only hosted snapshot. Never prints job copy or contact details.
import { readFileSync, writeFileSync } from "node:fs";
import { pathToFileURL } from "node:url";
import catalog from "../ui/lib/company-logo-catalog.json";
import domains from "../ui/lib/company-logo-domains.json";
import identities from "../ui/lib/company-logo-identities.json";
import { canonicalCompanyName, postingCompanyDomains } from "../ui/lib/company-logos";

type Posting = { id: string; company: string; url: string | null; apply_url: string | null; raw_jd: string | null };
type AuditEntry = { name: string; source: string; expected: string[]; postings: { id: string; evidence: string[]; conflicts: string[] }[] };
const domainMap: Record<string, string | null> = domains;
const identityMap: Record<string, { domains: string[] }> = identities;

export function auditLogoCollisions(rows: Posting[]): AuditEntry[] {
  const grouped = new Map<string, Posting[]>();
  for (const row of rows) {
    const name = canonicalCompanyName(row.company);
    const group = grouped.get(name) ?? [];
    group.push(row); grouped.set(name, group);
  }
  return [...new Set([...Object.keys(catalog), ...Object.keys(domains)])].sort().map(name => {
    const expected = Object.hasOwn(identityMap, name) ? identityMap[name].domains : domainMap[name] ? [domainMap[name]!] : [];
    return { name, source: Object.hasOwn(catalog, name) ? "catalog" : "domain map", expected,
      postings: (grouped.get(name) ?? []).map(row => {
        const evidence = postingCompanyDomains({ company: row.company, applyUrl: row.apply_url, url: row.url, rawJd: row.raw_jd }, expected);
        return { id: row.id, evidence, conflicts: expected.length ? evidence.filter(domain => !expected.includes(domain)) : [] };
      }) };
  });
}

if (process.argv[1] && import.meta.url === pathToFileURL(process.argv[1]).href) {
  const [input, output] = process.argv.slice(2);
  if (!input || !output) throw new Error("Usage: audit-logo-collisions.ts <private snapshot.json> <report.md>");
  const rows: Posting[] = JSON.parse(readFileSync(input, "utf8"));
  const entries = auditLogoCollisions(rows);
  const conflicts = entries.flatMap(entry => entry.postings.filter(p => p.conflicts.length).map(p => ({ name: entry.name, ...p })));
  const lines = ["# Logo name collision audit — 2026-10-07", "", "Generated by `scripts/audit-logo-collisions.ts`; do not edit the inventory by hand.", "",
    `SELECT-only hosted snapshot: ${rows.length} postings. Catalog: ${Object.keys(catalog).length} entries; domain map: ${Object.keys(domains).length}; union audited: ${entries.length}.`, "",
    "Query: `select id,company,url,apply_url,raw_jd from public.postings order by id` via the Supabase management API with `read_only: true`. Existing environment credential; no secret-manager prompts, hosted writes, homepage guesses, or Logo.dev calls.", "",
    `Detected ${conflicts.length} posting/domain mismatches against bound identities. Missing identity bindings are reported as unbound, not as proven collisions. Employer-like domain references are candidates; references to third-party tools are not proof of ownership.`, "",
    "The reported Doit/DoiT collision (listing suffix aae3e321) is confirmed by the task brief. The stored row has LinkedIn-only posting/apply URLs and no employer-like domain in its JD, so this snapshot cannot independently prove doit.app ownership. Doit now requires doit.com evidence for the DoiT catalog asset; that row renders initials. DoiT rows without domain evidence also render initials.", "",
    "Only Wix and Jeen.ai are explicitly marked unambiguous; competing employer-like domains veto their name-only exception. The six official-site catalog pins use domains recorded in the asset manifest; the Doit pin comes from the incident brief. Other catalog entries have no asset identity binding and cannot be selected by name. Existing map domains remain identity candidates and require posting evidence.", "",
    "## Posting/domain mismatches", "", "| Name | Posting id | Expected | Different domain |", "| --- | --- | --- | --- |",
    ...conflicts.map(p => `| ${p.name} | ${p.id} | ${entries.find(e => e.name === p.name)!.expected.join(", ")} | ${p.conflicts.join(", ")} |`), "",
    "## Complete entry inventory", "",
    "Every catalog/domain key is listed below. Hosted references include all matching postings; raw job copy and contact details are omitted. A dash means no candidate domain in posting URLs/JD. Null or unbound entries cannot infer an employer from its name.", "",
    "| Name | Source | Bound domains | Hosted posting ids and domain evidence |", "| --- | --- | --- | --- |",
    ...entries.map(e => `| ${e.name.replaceAll("|", "\\|")} | ${e.source} | ${e.expected.join(", ") || "unbound/null"} | ${e.postings.map(p => `${p.id}: ${p.evidence.join(", ") || "—"}`).join("; ") || "no matching postings"} |`), ""];
  writeFileSync(output, lines.join("\n"));
  console.log(JSON.stringify({ totalPostings: rows.length, entries: entries.length, matchedPostings: entries.reduce((sum, e) => sum + e.postings.length, 0), conflicts }, null, 2));
}
